#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# FactoryGuard - Azure Functions Deployment Package Verifier
# Validates that the Functions bundle is properly configured, builds cleanly,
# respects .funcignore, and does NOT bundle local node_modules or secrets.
# Prevents Kudu InvalidPackageContentException (Offset to Central Directory).
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FUNCTIONS_DIR="$WORKSPACE_ROOT/functions"
TMP_ZIP="/tmp/factoryguard-functions-test-pkg.zip"

echo "======================================================================"
echo "FactoryGuard - Functions Deployment Package Verification"
echo "======================================================================"

# 1. Verify functions/.funcignore exists and excludes node_modules
echo "[1/6] Checking functions/.funcignore..."
if [ ! -f "$FUNCTIONS_DIR/.funcignore" ]; then
  echo "FAIL: functions/.funcignore not found! This will cause VS Code to bundle node_modules (69+ MB)."
  exit 1
fi

if ! grep -q "^node_modules" "$FUNCTIONS_DIR/.funcignore"; then
  echo "FAIL: functions/.funcignore does NOT exclude node_modules/."
  exit 1
fi
echo "  ✓ functions/.funcignore exists and correctly excludes node_modules/"

# 2. Verify functions/package.json and entrypoint
echo "[2/6] Verifying functions/package.json..."
if [ ! -f "$FUNCTIONS_DIR/package.json" ]; then
  echo "FAIL: functions/package.json missing!"
  exit 1
fi
MAIN_ENTRY="$(node -e "console.log(require('$FUNCTIONS_DIR/package.json').main || '')")"
if [ "$MAIN_ENTRY" != "dist/src/index.js" ]; then
  echo "FAIL: functions/package.json main must be 'dist/src/index.js' (found: '$MAIN_ENTRY')."
  exit 1
fi
echo "  ✓ package.json main entry point is correctly set to dist/src/index.js"

# 3. Build Functions TypeScript
echo "[3/6] Building Functions project (npm run build)..."
(cd "$FUNCTIONS_DIR" && npm run build)

if [ ! -f "$FUNCTIONS_DIR/dist/src/index.js" ]; then
  echo "FAIL: functions/dist/src/index.js was not generated by TypeScript build!"
  exit 1
fi
echo "  ✓ TypeScript compiled cleanly to functions/dist/src/index.js"

# 4. Generate deployment package respecting .funcignore
echo "[4/6] Creating deployment package zip (simulating VS Code Azure Tools)..."
rm -f "$TMP_ZIP"

# Zip functions directory excluding patterns defined in .funcignore
(cd "$FUNCTIONS_DIR" && zip -rq "$TMP_ZIP" . \
  -x "node_modules/*" \
  -x ".git/*" \
  -x ".vscode/*" \
  -x "coverage/*" \
  -x "*.log" \
  -x "local.settings.json" \
  -x ".env*" \
  -x "tests/*" \
  -x "*.tsbuildinfo")

# 5. Inspect package contents
echo "[5/6] Inspecting zip package contents..."
ZIP_CONTENTS="$(unzip -l "$TMP_ZIP")"

# Check that node_modules is NOT inside
if echo "$ZIP_CONTENTS" | grep -F "node_modules/" > /dev/null; then
  echo "FAIL: node_modules detected inside deployment zip! Deployment will fail."
  rm -f "$TMP_ZIP"
  exit 1
fi
echo "  ✓ Zero local node_modules in package"

# Check that local secrets are NOT inside
if echo "$ZIP_CONTENTS" | awk '{print $NF}' | grep -E -q "^(local\.settings\.json|\.env|\.env\.local)$"; then
  echo "FAIL: Local settings or .env file detected inside deployment zip!"
  rm -f "$TMP_ZIP"
  exit 1
fi
echo "  ✓ Zero secrets or local.settings.json in package"

# Check required files ARE inside
if ! echo "$ZIP_CONTENTS" | grep -F "dist/src/index.js" > /dev/null; then
  echo "FAIL: dist/src/index.js missing from package!"
  rm -f "$TMP_ZIP"
  exit 1
fi

if ! echo "$ZIP_CONTENTS" | grep -F "host.json" > /dev/null; then
  echo "FAIL: host.json missing from package!"
  rm -f "$TMP_ZIP"
  exit 1
fi

if ! echo "$ZIP_CONTENTS" | grep -F "package.json" > /dev/null; then
  echo "FAIL: package.json missing from package!"
  rm -f "$TMP_ZIP"
  exit 1
fi
echo "  ✓ Required runtime files (dist/src/index.js, host.json, package.json) verified"

# 6. Verify package size
echo "[6/6] Validating package size..."
PKG_SIZE_BYTES="$(wc -c < "$TMP_ZIP" | tr -d ' ')"
PKG_SIZE_KB=$(( PKG_SIZE_BYTES / 1024 ))

echo "  ✓ Zip Package Size: ${PKG_SIZE_KB} KB (${PKG_SIZE_BYTES} bytes)"

# Clean up
rm -f "$TMP_ZIP"

if [ "$PKG_SIZE_KB" -gt 5000 ]; then
  echo "WARNING: Deployment package is larger than 5 MB (${PKG_SIZE_KB} KB). Check for unneeded files."
  exit 1
fi

echo "======================================================================"
echo "SUCCESS: Functions deployment bundle is verified and production-ready!"
echo "Package size is ~${PKG_SIZE_KB} KB (vs previous 69.2 MB failure)."
echo "VS Code Azure Functions deployment path will deploy cleanly without Kudu errors."
echo "======================================================================"
